### ISSUE TITLE
symmetric tumor spread in `bilateral` does not trigger tensor deletion of `_transition_tensor`

### ISSUE THREAD

**Issue by YoelPH** [rmnldwg/lymph#69]
I found another issue which I can't quite figure out yet. 

In the `bilateral.py` there is the option to set up tumor edge symmetry (e.g. for a  "tumor on the midline" model). However, assigning new base spread parameters (after setting them initially) does not trigger a deletion of the `_transition_tensor` in the edges connecting tumor to LNL. Interestingly, this issue does not show up for edges which connect LNLs (when setting LNL transition symmetry). 
I tried to figure out whether there is a difference how the edges are treated/whether there is a different callback between tumor edges and LNL edges, but found none. 
The parameters are correctly assigned to the contralateral edges, but the callback seems not to function properly. I will try to find the origin of this bug and report it here.

**Comment by rmnldwg** [comment]
I found the mistake. The code below, in analogy to [these lines](https://github.com/rmnldwg/lymph/blob/12c3e8a51e9e4c22cf4913455f8718ffe1964c81/lymph/models/bilateral.py#L236C1-L239C10), is wrong because this

```python
my_list = (
    [1,2,3] if truthy_variable else []
    + [4,5,6] if truthy_variable else []
)
```

is actually equivalent to

```python
my_list = (
    [1,2,3] if truthy_variable else [] + [4,5,6] if truthy_variable else []
)
```

which means that the `+ [4,5,6] ...` is part of the `else` statement and NOT a new line that gets executed regardless of the first `if-else` block.

I corrected it to

```python
my_list = (
    ([1,2,3] if truthy_variable else [])
    + ([4,5,6] if truthy_variable else [])
)
```

To make sure the stuff in the parentheses gets evaluated first.

This also explains why everything worked fine until you set the tumor spread to be symmetric: If the tumor spread is not symmetric, everything after the first `else` got executed, which was coincidentally the intended outcome.

The fix is still in the `dev` branch for now.

**Comment by YoelPH** [comment]
Perfect, thank you very much!
I assumed the problem to be deeper inside the code, as somehow the edges still got assigned new spread probabilities.

**Comment by rmnldwg** [comment]
What cannot be recreated now? Is there still an issue with the assignment/synchronization of the parameters?

**Comment by YoelPH** [comment]
Okay, I just tried your fix, unfortunately the problem persists. The bug you fixed did not solve the underlying problem. If I reassign ipsilateral tumor spread parameters, the parameters in the contralateral side still change, but the transition tensor is not updated...
(I meant that I could not recreate my problem from before, but now that I looked at it more thoroughly I found the same issue as before).

**Comment by YoelPH** [comment]
I found the "new" problem.
Assigning as `ipsi_primary_to_III_spread': 0.07` only updates the Tensor on the contralateral side at first assignment. If I use: `primary_to_III_spread': 0.07`, also the contralateral tensor is updated. I do not understand why a tensor deletion callback is not triggered, even though the parameter for the contralateral edge is updated, but with "correct" assignment the problem can be circumvented.

**Comment by rmnldwg** [comment]
Oh good Lord 😅

Alright, thanks for the thorough investigation. I think I have an idea of how to solve it... 🤔

**Comment by YoelPH** [comment]
This sounds like an amazing idea!
Tomorrow I will merge your changes with my code and test the essentials and make it compatible with my midline code.
I think after this step we can discuss whether the midline model I implemented fits nicely into the existing code base. (even though the caching might need to be overworked as well, as I modelled it according to the bilateral code)

**Comment by YoelPH** [comment]
First test on the binary midline model were successful. I am finishing the trinary analysis, but it looks like it works as intended 👍🏽

**Comment by rmnldwg** [comment]
Just noticed a small thing I forgot: [This line](https://github.com/rmnldwg/lymph/blob/dev/lymph%2Fmodels%2Funilateral.py#L479) should be `@property` and _NOT_ `@cached_property`.
